### ISSUE TITLE
KeepInv not working.

### ISSUE THREAD

**Issue by CrystalizedFuture** [mk7a-mc/ItemSoulBind#37]
**Plugin version**
Get plugin version with /ver ItemSoulBind
1.6.0
**Spigot Version**
Get spigot version with /ver
This server is running Paper version git-Paper-177 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 1bbd273)

**Plugin Configuration**
<details>
  <summary>File</summary>
   paste your plugin config here
# Binds when tool is used: used to break block, sword used to hit entity
bindOnUse: false
bouString: "&9Soul binds on use"
# Binds when armor is equipped through in-hand right click
bindOnEquip: false
boeString: "&9Soul binds on equip"
# Binds when item is picked up
bindOnPickup: false
bopString: "&9Soul binds on pickup"

# Disable soul bind particle+sound effects
disableEffects: false

# Display message in item lore of soul bound item
# Use %username% for player name placeholder
displayLoreMsg: true
loreMsg: "&9Soul bound to %username%"
# Similarly for group binds, using placeholder %group%
displayLoreMsgGroup: true
loreMsgGroup: "&9Soul bound to group %group%"

# Log player detected with item soul bound to another player in console
consoleLogDetection: true

# Prevents placing soul bound blocks
preventPlacing: false

# Prevents crafting with soul bound items
preventCraft: false

# Prevents enchanting with soul bound items
preventEnchant: false

# Prevents anvil use with soul bound items
preventAnvil: false

# Blocks commands when soul bound item is held in hand
# Only provide the first part of the command, e.g. for "/auction sell" :
blockedCommands:
  - "auction"

**Plugins List**
If you are running other plugins, please provide a list.
![image](https://user-images.githubusercontent.com/68520318/195988130-4b8c84a9-2b18-4ad5-a663-fcc63f822d04.png)

**To Reproduce**
When we do /gamerule keepInventory true, players do not receive their items when they die. When they go back to the place where they died, their items are completely gone.

**Expected behavior**
When players die, they get their entire inv back.

**Comment by mk7a** [comment]
Unable to reproduce bug. 
Paper 1.19.2 git-Paper-177, plugin version 1.6.0

**Trial 1**
keepInventory: true
permission itemsoulbind.keepondeath: false
Items: One soul bound, one non soul bound
Method: /kill 
Result: After death both items still in inventory

**Trial 2**
keepInventory: true
permission itemsoulbind.keepondeath: true (luckperms)
Items: One soul bound, one non soul bound
Method: /kill 
Result: After death both items still in inventory

If there are steps missing in trials, let me know. 
Otherwise I suggest making a copy of the server, disable other plugins one by one to find possible conflict.
